[phases.setup]
aptPkgs = [
    "python3.12",
    "python3.12-venv",
    "python3.12-dev",
    "python3-pip",
    "libcairo2-dev",
    "pkg-config",
    "libpango1.0-dev",
    "libgdk-pixbuf2.0-dev",
    "libglib2.0-dev",
    "libfontconfig1-dev",
    "libfreetype6-dev",
    "libffi-dev",
    "postgresql-client",
    "meson",
    "ninja-build",
]

[phases.install]
cmds = [
    "python3.12 -m venv /opt/venv && . /opt/venv/bin/activate && pip install --no-build-isolation pycairo && pip install -r requirements.txt"
]