[phases.setup]
nixPkgs = [
    "python312",
    "postgresql",
    "pkg-config",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "glib",
    "fontconfig",
    "freetype",
    "libffi",
]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]