# Generated by Django 6.0.3 on 2026-03-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['name'], 'verbose_name_plural': 'Job Titles'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['department__name', 'name'], 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Phase 6 transitional field. This is the new correct dependency for Department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Legacy transitional field only. Will be removed after forms/views/admin are refactored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_departments', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Phase 6 transitional field. New correct primary dependency for Job Title.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional. Use this only when the job title is section-specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='organization.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_branch_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('department', 'section', 'name'), name='unique_job_title_per_department_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_section_name_per_department'),
        ),
    ]
