# Generated by Django 6.0.3 on 2026-03-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_options_alter_jobtitle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['company__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['company__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['department__company__name', 'department__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['department__company__name', 'department__name', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_name_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_name_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='jobtitle',
            name='unique_job_title_per_department_section',
        ),
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section_name_per_department',
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'name')},
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('department', 'section', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'name')},
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_departments', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='job_titles', to='organization.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_titles', to='organization.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='organization.department'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
    ]
