# Generated by Django 6.0.3 on 2026-03-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_branch_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['section__department__company__name', 'section__department__name', 'section__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('section', 'name')},
        ),
    ]
