# Generated by Django 6.0.3 on 2026-04-05 07:42

import django.core.validators
import django.db.models.deletion
import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_branchdocument_branchdocumentrequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchdocumentrequirement',
            options={'ordering': ['branch__company__name', 'branch__name', 'document_type', 'title', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='branchdocumentrequirement',
            unique_together={('branch', 'document_type')},
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=organization.models.branch_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=organization.models.company_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='branchdocumentrequirement',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BranchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('legal', 'Legal Document'), ('ad_license', 'Ad License'), ('store_license', 'Store License'), ('municipality', 'Municipality / Permit'), ('lease', 'Lease / Contract'), ('civil_defense', 'Civil Defense / Safety'), ('insurance', 'Insurance'), ('service', 'Service Contract'), ('other', 'Other')], default='other', max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=organization.models.branch_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'txt'])])),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organization.branch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
