# Generated by Django 6.0.3 on 2026-04-24 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_branch_attendance_location_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='branchdocument',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Branch Document', 'verbose_name_plural': 'Branch Documents'},
        ),
        migrations.AlterModelOptions(
            name='branchdocumentrequirement',
            options={'ordering': ['branch__company__name', 'branch__name', 'document_type', 'title', 'id'], 'verbose_name': 'Branch Document Requirement', 'verbose_name_plural': 'Branch Document Requirements'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['section__department__company__name', 'section__department__name', 'section__name', 'name'], 'verbose_name': 'Job Title', 'verbose_name_plural': 'Job Titles'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['department__company__name', 'department__name', 'name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='attendance_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='attendance_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='attendance_radius_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Allowed attendance radius in meters from the fixed branch point.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_active', 'name'], name='organizatio_company_30da7e_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city', 'is_active'], name='organizatio_city_895396_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdocument',
            index=models.Index(fields=['branch', 'document_type', '-created_at'], name='organizatio_branch__c8a587_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdocument',
            index=models.Index(fields=['expiry_date', 'is_required'], name='organizatio_expiry__5b00d6_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdocumentrequirement',
            index=models.Index(fields=['branch', 'is_active', 'document_type'], name='organizatio_branch__1ce909_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdocumentrequirement',
            index=models.Index(fields=['is_mandatory', 'is_active'], name='organizatio_is_mand_83cf99_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'name'], name='organizatio_is_acti_990376_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'is_active', 'name'], name='organizatio_company_abbd69_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['branch', 'is_active'], name='organizatio_branch__5e5dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['department', 'is_active', 'name'], name='organizatio_departm_2fb4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['section', 'is_active', 'name'], name='organizatio_section_4a9874_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['department', 'is_active', 'name'], name='organizatio_departm_0b0276_idx'),
        ),
    ]
