# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces legacy unique_together declarations with named
# UniqueConstraint objects for organization hierarchy models. It preserves the
# same uniqueness behavior that existing migrations already enforced, while
# giving each database rule a stable, descriptive name for future maintenance.
#
# No data backfill is required because this does not introduce a new uniqueness
# rule; it renames/re-expresses existing database semantics.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='branchdocumentrequirement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='org_branch_company_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchdocumentrequirement',
            constraint=models.UniqueConstraint(fields=('branch', 'document_type'), name='org_branch_doc_req_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='org_dept_company_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='org_jobtitle_section_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='org_section_dept_name_uniq'),
        ),
    ]
