# Generated by Django 6.0.3 on 2026-03-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0002_alter_department_options_alter_jobtitle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Transitional during hierarchy refactor. Will be enforced later.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department'),
            preserve_default=False,
        ),
    ]
