# Generated by Django 6.0.3 on 2026-03-23 19:55

import django.core.validators
import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_alter_employee_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('general', 'General'), ('contract', 'Contract'), ('id', 'ID / Civil Documents'), ('certificate', 'Certificate'), ('payroll', 'Payroll'), ('medical', 'Medical'), ('other', 'Other')], default='general', max_length=30)),
                ('file', models.FileField(upload_to=employees.models.employee_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'txt'])])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
