# Generated by Django 6.0.3 on 2026-03-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('probation', 'Probation'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='separation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='separation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_notes',
            field=models.TextField(blank=True),
        ),
    ]
