# Generated by Django 6.0.3 on 2026-03-23 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_employment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='probation_end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='separation_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='separation_reason',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status_effective_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status_notes',
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('system', 'System'), ('profile', 'Profile'), ('note', 'Note'), ('document', 'Document'), ('status', 'Status'), ('onboarding', 'Onboarding'), ('separation', 'Separation'), ('other', 'Other')], default='note', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='employees.employee')),
            ],
            options={
                'ordering': ['-event_date', '-created_at', '-id'],
            },
        ),
    ]
