# Generated by Django 6.0.3 on 2026-03-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reference_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
