# Generated by Django 6.0.3 on 2026-03-24 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeeleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('absence', 'Absence'), ('lateness', 'Lateness'), ('warning', 'Warning'), ('memo', 'Memo'), ('disciplinary_action', 'Disciplinary Action'), ('commendation', 'Commendation'), ('other', 'Other')], default='memo', max_length=30)),
                ('action_date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-action_date', '-created_at', '-id'],
            },
        ),
    ]
