# Generated by Django 6.0.3 on 2026-03-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeeactionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
