# Generated by Django 6.0.3 on 2026-03-25 00:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_user_employeeleave_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('day_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('weekly_off', 'Weekly Off'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('sick_leave', 'Sick Leave'), ('holiday', 'Holiday'), ('other', 'Other')], default='present', max_length=20)),
                ('clock_in_time', models.TimeField(blank=True, null=True)),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_departure_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('is_paid_day', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('leave', 'Leave Workflow'), ('action', 'Action Record'), ('system', 'System')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_ledgers', to='employees.employee')),
                ('linked_action_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_ledger_entries', to='employees.employeeactionrecord')),
                ('linked_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_ledger_entries', to='employees.employeeleave')),
            ],
            options={
                'ordering': ['-attendance_date', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_date')],
            },
        ),
    ]
