# Generated by Django 6.0.3 on 2026-03-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeeattendanceledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='linked_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_documents', to='employees.employeeleave'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='event_type',
            field=models.CharField(choices=[('profile', 'Profile Update'), ('transfer', 'Placement Change'), ('document', 'Document Event'), ('status', 'Status / Workflow Event'), ('note', 'Manual Note')], default='note', max_length=20),
        ),
    ]
