# Generated by Django 6.0.3 on 2026-03-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeedocument_linked_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='civil_id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_id_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
