# Generated by Django 6.0.3 on 2026-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_civil_id_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('emergency_leave', 'Emergency Leave'), ('unpaid_leave', 'Unpaid Leave')], default='active', max_length=30),
        ),
    ]
