# Generated by Django 6.0.3 on 2026-03-26 18:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendanceledger',
            name='day_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('weekly_off', 'Weekly Off'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('sick_leave', 'Sick Leave'), ('holiday', 'Holiday'), ('other', 'Other')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_day_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('weekly_off', 'Weekly Off'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('sick_leave', 'Sick Leave'), ('holiday', 'Holiday'), ('other', 'Other')], default='present', max_length=20)),
                ('requested_clock_in_time', models.TimeField(blank=True, null=True)),
                ('requested_clock_out_time', models.TimeField(blank=True, null=True)),
                ('requested_scheduled_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('requested_late_minutes', models.PositiveIntegerField(default=0)),
                ('requested_early_departure_minutes', models.PositiveIntegerField(default=0)),
                ('requested_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('requested_is_paid_day', models.BooleanField(default=True)),
                ('request_reason', models.TextField()),
                ('review_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='employees.employee')),
                ('linked_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='employees.employeeattendanceledger')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
