# Generated by Django 6.0.3 on 2026-03-30 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employeeattendanceledger_day_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendancecorrection',
            old_name='reviewed_at',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='employeeattendancecorrection',
            name='requested_is_paid_day',
        ),
        migrations.AddField(
            model_name='employeeattendancecorrection',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeattendancecorrection',
            name='requested_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeattendancecorrection',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employeeattendancecorrection',
            name='linked_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='employees.employeeattendanceledger'),
        ),
        migrations.AlterField(
            model_name='employeeattendancecorrection',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_attendance_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeattendancecorrection',
            name='requested_day_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('weekly_off', 'Weekly Off'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('sick_leave', 'Sick Leave'), ('holiday', 'Holiday'), ('other', 'Other')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeattendancecorrection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeattendancecorrection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeattendanceledger',
            name='day_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('weekly_off', 'Weekly Off'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('sick_leave', 'Sick Leave'), ('holiday', 'Holiday'), ('other', 'Other')], default='present', max_length=20),
        ),
    ]
