# Generated by Django 6.0.3 on 2026-03-30 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_rename_reviewed_at_employeeattendancecorrection_applied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='current_stage',
            field=models.CharField(choices=[('supervisor_review', 'Supervisor Review'), ('operations_review', 'Operations Review'), ('hr_review', 'HR Review'), ('final_approved', 'Final Approved'), ('final_rejected', 'Final Rejected'), ('cancelled', 'Cancelled')], default='supervisor_review', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='operations_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='operations_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='operations_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_reviewed_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviewed_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
