# Generated by Django 6.0.3 on 2026-04-01 18:24

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employeeleave_current_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequiredSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('passport_copy', 'Passport Copy'), ('civil_id_copy', 'Civil ID Copy'), ('contract_copy', 'Contract Copy'), ('medical_document', 'Medical Document'), ('certificate', 'Certificate'), ('general_document', 'General Document'), ('other', 'Other')], default='general_document', max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('instructions', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('employee_note', models.TextField(blank=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to=employees.models.employee_submission_request_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'txt'])])),
                ('response_reference_number', models.CharField(blank=True, max_length=120)),
                ('response_issue_date', models.DateField(blank=True, null=True)),
                ('response_expiry_date', models.DateField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_required_submissions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_submissions', to='employees.employee')),
                ('fulfilled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_requests', to='employees.employeedocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_required_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', '-id'],
            },
        ),
    ]
