# Generated by Django 6.0.3 on 2026-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employeerequiredsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='civil_id_reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
