# Generated by Django 6.0.3 on 2026-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employeeattendanceledger_shift_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendanceledger',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='employeeattendanceledger',
            name='shift_start_time',
        ),
        migrations.AddField(
            model_name='employeeattendanceledger',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Shift'), ('middle', 'Middle Shift'), ('night', 'Night Shift')], max_length=20, null=True),
        ),
    ]
