# Generated by Django 6.0.3 on 2026-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_remove_employeeattendanceledger_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
