# Generated by Django 6.0.3 on 2026-04-09 03:28

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_employee_birth_date_employee_marital_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='hr_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_employee_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_delivery_file',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.employee_leave_delivery_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_delivery_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_delivery_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave'), ('salary_certificate', 'Salary Certificate'), ('employment_certificate', 'Employment Certificate'), ('other', 'Other Request')], default='annual', max_length=50),
        ),
    ]
