# Generated by Django 6.0.3 on 2026-04-09 13:21

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_employeeleave_hr_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleave',
            name='hr_delivered_at',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='hr_delivered_by',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='hr_delivery_file',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='hr_delivery_note',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='hr_delivery_title',
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave'), ('other', 'Other')], default='annual', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('salary_certificate', 'Salary Certificate'), ('salary_transfer', 'Salary Transfer Letter'), ('experience_certificate', 'Experience Certificate'), ('noc_letter', 'No Objection Letter'), ('hr_letter', 'HR Letter'), ('other', 'Other')], default='other', max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('request_note', models.TextField(blank=True)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('management_note', models.TextField(blank=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to=employees.models.employee_management_request_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'txt'])])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_document_requests', to=settings.AUTH_USER_MODEL)),
                ('delivered_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_employee_document_requests', to='employees.employeedocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', '-id'],
            },
        ),
    ]
