# Generated by Django 6.0.3 on 2026-04-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_branchweeklyscheduletheme'),
        ('organization', '0008_alter_branch_image_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAttendanceShiftSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_key', models.CharField(choices=[('morning', 'Morning Shift'), ('middle', 'Middle Shift'), ('night', 'Night Shift')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_shift_settings', to='organization.branch')),
                ('linked_duty_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_attendance_shifts', to='employees.branchweeklydutyoption')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('branch', 'shift_key')},
            },
        ),
    ]
