# Generated by Django 6.0.3 on 2026-04-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_attendance_location_validation_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchAttendanceShiftSetting',
        ),
    ]
