# Generated by Django 6.0.3 on 2026-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_delete_branchattendanceshiftsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendanceevent',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('middle', 'Middle Shift'), ('night', 'Night Shift'), ('nine_to_five', '9 am to 5 pm'), ('twelve_to_eight', '12 pm to 8 pm'), ('one_to_nine', '1 pm to 9 pm'), ('two_to_ten', '2 pm to 10 pm'), ('three_to_eleven', '3 pm to 11 pm'), ('four_to_midnight', '4 pm to 12 am'), ('morning_standard', 'Morning shift'), ('middle_standard', 'Middle shift'), ('evening_standard', 'Evening shift')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeattendanceledger',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Shift'), ('middle', 'Middle Shift'), ('night', 'Night Shift'), ('nine_to_five', '9 am to 5 pm'), ('twelve_to_eight', '12 pm to 8 pm'), ('one_to_nine', '1 pm to 9 pm'), ('two_to_ten', '2 pm to 10 pm'), ('three_to_eleven', '3 pm to 11 pm'), ('four_to_midnight', '4 pm to 12 am'), ('morning_standard', 'Morning shift'), ('middle_standard', 'Middle shift'), ('evening_standard', 'Evening shift')], max_length=20, null=True),
        ),
    ]
