# Generated by Django 6.0.3 on 2026-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_alter_employeeattendanceevent_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('hajj', 'Hajj Leave'), ('lieu', 'Lieu Leave'), ('emergency', 'Emergency Leave'), ('other', 'Other')], default='annual', max_length=20),
        ),
    ]
