# Generated by Django 6.0.3 on 2026-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_overtimerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_kuwaiti_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pifss_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
