# Generated by Django 6.0.3 on 2026-04-24 12:14

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_employee_is_kuwaiti_national_and_more'),
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id', 'full_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeactionrecord',
            options={'ordering': ['-action_date', '-created_at', '-id'], 'verbose_name': 'Employee Action Record', 'verbose_name_plural': 'Employee Action Records'},
        ),
        migrations.AlterModelOptions(
            name='employeeattendanceledger',
            options={'ordering': ['-attendance_date', '-created_at', '-id'], 'verbose_name': 'Employee Attendance Ledger', 'verbose_name_plural': 'Employee Attendance Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='employeecontract',
            options={'ordering': ['-is_active', '-start_date', '-id'], 'verbose_name': 'Employee Contract', 'verbose_name_plural': 'Employee Contracts'},
        ),
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'ordering': ['-start_date', '-created_at', '-id'], 'verbose_name': 'Employee Leave', 'verbose_name_plural': 'Employee Leaves'},
        ),
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Overtime Request', 'verbose_name_plural': 'Overtime Requests'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='total_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='hours_requested',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'is_active', 'employment_status'], name='employees_e_company_15f56f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch', 'is_active', 'full_name'], name='employees_e_branch__270446_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_active', 'full_name'], name='employees_e_departm_48df9a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeactionrecord',
            index=models.Index(fields=['employee', 'status', '-action_date'], name='employees_e_employe_c16990_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeactionrecord',
            index=models.Index(fields=['action_type', 'severity', '-action_date'], name='employees_e_action__965831_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendanceledger',
            index=models.Index(fields=['employee', '-attendance_date'], name='employees_e_employe_014bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendanceledger',
            index=models.Index(fields=['day_status', '-attendance_date'], name='employees_e_day_sta_46c3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendanceledger',
            index=models.Index(fields=['source', '-attendance_date'], name='employees_e_source_8fc7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecontract',
            index=models.Index(fields=['employee', 'is_active', '-start_date'], name='employees_e_employe_b8c69c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecontract',
            index=models.Index(fields=['end_date', 'is_active'], name='employees_e_end_dat_18c78e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeleave',
            index=models.Index(fields=['employee', 'status', '-start_date'], name='employees_e_employe_b34fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeleave',
            index=models.Index(fields=['status', 'current_stage', '-created_at'], name='employees_e_status_812042_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeleave',
            index=models.Index(fields=['leave_type', 'status', 'start_date'], name='employees_e_leave_t_73ff0c_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['employee', 'status', '-date'], name='employees_o_employe_86e75a_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['status', '-created_at'], name='employees_o_status_1f3a85_idx'),
        ),
    ]
