# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces legacy unique_together declarations with named
# UniqueConstraint objects for branch schedule/grid models. It keeps the same
# uniqueness rules already represented by previous migrations, but gives them
# stable names so future constraint changes are easier to reason about.
#
# No data backfill is required because this migration does not add stricter
# uniqueness than the existing schema already intended.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_employee_options_and_more'),
        ('organization', '0011_alter_branch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchschedulegridcell',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='branchschedulegridheader',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='branchschedulegridrow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='branchweeklydutyoption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='branchweeklypendingoff',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='branchweeklyscheduleentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branchschedulegridcell',
            constraint=models.UniqueConstraint(fields=('branch', 'row_index', 'column_index'), name='emp_grid_cell_branch_row_col_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchschedulegridheader',
            constraint=models.UniqueConstraint(fields=('branch', 'column_index'), name='emp_grid_header_branch_col_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchschedulegridrow',
            constraint=models.UniqueConstraint(fields=('branch', 'row_index'), name='emp_grid_row_branch_row_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchweeklydutyoption',
            constraint=models.UniqueConstraint(fields=('branch', 'label'), name='emp_duty_option_branch_label_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchweeklypendingoff',
            constraint=models.UniqueConstraint(fields=('branch', 'employee', 'week_start'), name='emp_pending_off_branch_emp_week_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchweeklyscheduleentry',
            constraint=models.UniqueConstraint(fields=('branch', 'employee', 'schedule_date'), name='emp_weekly_entry_branch_emp_date_uniq'),
        ),
    ]
