# Generated by Django 6.0.3 on 2026-04-23 04:58

import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidateattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.models.candidate_offer_letter_upload_to),
        ),
        migrations.AddField(
            model_name='candidateinterview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('hold', 'Hold'), ('no', 'No')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateinterview',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
