# Generated by Django 6.0.3 on 2026-04-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_offer_letter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='offer_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
