# Generated by Django 6.0.3 on 2026-04-23 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_offer_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='offer_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending Response'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_recruitment_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CandidateInterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('hold', 'Hold'), ('no', 'No')], max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='recruitment.candidateinterview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_interview_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('interview', 'interviewer')},
            },
        ),
    ]
