# Generated by Django 6.0.3 on 2026-04-24 12:14

import django.core.validators
import recruitment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_employee_options_and_more'),
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
        ('recruitment', '0006_candidate_offer_decision_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-applied_at', 'full_name'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='candidateattachment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Candidate Attachment', 'verbose_name_plural': 'Candidate Attachments'},
        ),
        migrations.AlterModelOptions(
            name='candidateinterview',
            options={'ordering': ['scheduled_at', 'id'], 'verbose_name': 'Candidate Interview', 'verbose_name_plural': 'Candidate Interviews'},
        ),
        migrations.AlterModelOptions(
            name='candidateinterviewfeedback',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Candidate Interview Feedback', 'verbose_name_plural': 'Candidate Interview Feedback'},
        ),
        migrations.AlterModelOptions(
            name='candidatestageaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Candidate Stage Action', 'verbose_name_plural': 'Candidate Stage Actions'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_date', '-created_at', 'title'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(upload_to=recruitment.models.candidate_cv_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.models.candidate_offer_letter_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='candidateattachment',
            name='file',
            field=models.FileField(upload_to=recruitment.models.candidate_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='candidateinterview',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='candidateinterviewfeedback',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job_posting', 'status', '-applied_at'], name='recruitment_job_pos_f70110_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['recruiter_owner', 'status'], name='recruitment_recruit_b389de_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['offer_status', 'offer_expiry_date'], name='recruitment_offer_s_d7094a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateattachment',
            index=models.Index(fields=['candidate', '-created_at'], name='recruitment_candida_92a8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateinterview',
            index=models.Index(fields=['candidate', 'scheduled_at'], name='recruitment_candida_2537a1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateinterview',
            index=models.Index(fields=['interviewer', 'scheduled_at'], name='recruitment_intervi_e35d51_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatestageaction',
            index=models.Index(fields=['candidate', '-created_at'], name='recruitment_candida_2d0464_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatestageaction',
            index=models.Index(fields=['stage', '-created_at'], name='recruitment_stage_f4ccbc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', '-posted_date'], name='recruitment_status_6a82a4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['department', 'status'], name='recruitment_departm_6f61b6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['branch', 'status'], name='recruitment_branch__bf5c91_idx'),
        ),
    ]
