# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces the legacy unique_together declaration on candidate
# interview feedback with an equivalent named UniqueConstraint. The rule remains
# one feedback row per interview/interviewer pair.
#
# No data backfill is required because the same uniqueness rule was already
# represented by the previous schema.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_candidate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateinterviewfeedback',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='candidateinterviewfeedback',
            constraint=models.UniqueConstraint(fields=('interview', 'interviewer'), name='recruit_feedback_interviewer_uniq'),
        ),
    ]
