# Generated by Django 6.0.3 on 2026-04-24 12:14

import django.core.validators
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_employee_options_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseclaim',
            options={'ordering': ['-expense_date', '-created_at', '-id'], 'verbose_name': 'Expense Claim', 'verbose_name_plural': 'Expense Claims'},
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='currency',
            field=models.CharField(default='KWD', max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a 3-letter ISO code.', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=finance.models.expense_receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['employee', 'status', '-expense_date'], name='finance_exp_employe_f78778_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['status', '-created_at'], name='finance_exp_status_5d1eab_idx'),
        ),
    ]
