# Generated by Django 6.0.3 on 2026-04-24 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('employees', '0042_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetassignment',
            options={'ordering': ['-assigned_date', '-id'], 'verbose_name': 'Asset Assignment', 'verbose_name_plural': 'Asset Assignments'},
        ),
        migrations.AlterModelOptions(
            name='companyasset',
            options={'ordering': ['asset_code', 'name'], 'verbose_name': 'Company Asset', 'verbose_name_plural': 'Company Assets'},
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['asset', 'returned_date'], name='assets_asse_asset_i_0c474d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee', '-assigned_date'], name='assets_asse_employe_69172b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['assigned_by', '-created_at'], name='assets_asse_assigne_c9b768_idx'),
        ),
        migrations.AddIndex(
            model_name='companyasset',
            index=models.Index(fields=['category', 'is_available'], name='assets_comp_categor_df6484_idx'),
        ),
        migrations.AddIndex(
            model_name='companyasset',
            index=models.Index(fields=['condition', 'is_available'], name='assets_comp_conditi_5d924d_idx'),
        ),
        migrations.AddIndex(
            model_name='companyasset',
            index=models.Index(fields=['serial_number'], name='assets_comp_serial__108dab_idx'),
        ),
    ]
