# Generated by Django 6.0.3 on 2026-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hrannouncement',
            index=models.Index(fields=['audience', 'is_active', '-published_at'], name='hr_hrannoun_audienc_e3b8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['company', 'category', 'is_active'], name='hr_hrpolicy_company_f8ec89_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['is_active', 'effective_date'], name='hr_hrpolicy_is_acti_6ec927_idx'),
        ),
    ]
