# Generated by Django 6.0.3 on 2026-04-24 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_employee_options_and_more'),
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
        ('performance', '0002_performancereviewcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-cycle__period_start', '-updated_at', '-id'], 'verbose_name': 'Performance Review', 'verbose_name_plural': 'Performance Reviews'},
        ),
        migrations.AlterModelOptions(
            name='performancereviewcomment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Performance Review Comment', 'verbose_name_plural': 'Performance Review Comments'},
        ),
        migrations.AlterModelOptions(
            name='reviewcycle',
            options={'ordering': ['-period_start', '-id'], 'verbose_name': 'Review Cycle', 'verbose_name_plural': 'Review Cycles'},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['cycle', 'status'], name='performance_cycle_i_e7a370_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'status'], name='performance_employe_57a8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['reviewer', 'status'], name='performance_reviewe_2856c2_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereviewcomment',
            index=models.Index(fields=['review', 'created_at'], name='performance_review__f0504f_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcycle',
            index=models.Index(fields=['company', 'status', '-period_start'], name='performance_company_f99953_idx'),
        ),
    ]
