# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces the legacy unique_together declaration on
# PerformanceReview with an equivalent named UniqueConstraint. The rule remains
# one review per cycle and employee.
#
# No data backfill is required because this preserves an existing uniqueness
# rule instead of introducing a new one.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_alter_branchschedulegridcell_unique_together_and_more'),
        ('performance', '0003_alter_performancereview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='perf_review_cycle_employee_uniq'),
        ),
    ]
