# Generated by Django 6.0.3 on 2026-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('supervisor', 'Supervisor'), ('operations_manager', 'Operations Manager'), ('employee', 'Employee')], help_text='Business role used for HR workflow permissions.', max_length=30),
        ),
    ]
