# Generated by Django 6.0.3 on 2026-04-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance_manager', 'Finance Manager'), ('supervisor', 'Supervisor'), ('operations_manager', 'Operations Manager'), ('employee', 'Employee')], help_text='Business role used for HR workflow permissions.', max_length=30),
        ),
    ]
