from django.urls import path

from .views import (
    EmployeeCreateView,
    EmployeeDeleteView,
    EmployeeDetailView,
    EmployeeListView,
    EmployeeUpdateView,
    EmployeeTransferView,
    attendance_management,
    employee_action_record_create,
    employee_admin_action_center,
    employee_attendance_correction_apply,
    employee_attendance_correction_create,
    employee_attendance_correction_reject,
    employee_attendance_create,
    employee_document_create,
    employee_document_request_create,
    employee_document_request_review,
    employee_document_request_cancel,
    employee_document_delete,
    employee_document_update,
    employee_history_create,
    employee_leave_approve,
    employee_leave_cancel,
    employee_leave_create,
    employee_leave_reject,
    employee_required_submission_create,
    employee_required_submission_review,
    employee_required_submission_submit,
    employee_requests_overview,
    employee_profile_employee_information_update,
    employee_profile_identity_information_update,
    employee_status_update,
    get_branches_by_company,
    get_departments_by_company,
    get_job_titles_by_context,
    get_sections_by_department,
)

app_name = "employees"

urlpatterns = [
    path("", EmployeeListView.as_view(), name="employee_list"),
    path("create/", EmployeeCreateView.as_view(), name="employee_create"),
    path("attendance/", attendance_management, name="attendance_management"),
    path("action-center/", employee_admin_action_center, name="employee_admin_action_center"),
    path("requests-overview/", employee_requests_overview, name="employee_requests_overview"),

    # Current AJAX endpoints
    path("ajax/departments-by-company/", get_departments_by_company, name="get_departments_by_company"),
    path("ajax/branches-by-company/", get_branches_by_company, name="get_branches_by_company"),
    path("ajax/sections-by-department/", get_sections_by_department, name="get_sections_by_department"),
    path("ajax/job-titles-by-context/", get_job_titles_by_context, name="get_job_titles_by_context"),

    # Backward-compatible aliases used by existing live templates
    path("ajax/departments-by-company/", get_departments_by_company, name="ajax_departments_by_company"),
    path("ajax/branches-by-company/", get_branches_by_company, name="ajax_branches_by_company"),
    path("ajax/sections-by-department/", get_sections_by_department, name="ajax_sections_by_department"),
    path("ajax/job-titles-by-context/", get_job_titles_by_context, name="job_titles_by_context"),

    path("ajax/departments-by-company/", get_departments_by_company, name="departments_by_company"),
    path("ajax/branches-by-company/", get_branches_by_company, name="branches_by_company"),
    path("ajax/sections-by-department/", get_sections_by_department, name="sections_by_department"),
    path("ajax/job-titles-by-context/", get_job_titles_by_context, name="job_titles_by_department"),

    path("<int:pk>/", EmployeeDetailView.as_view(), name="employee_detail"),
    path("<int:pk>/update/", EmployeeUpdateView.as_view(), name="employee_update"),
    path("<int:pk>/transfer/", EmployeeTransferView.as_view(), name="employee_transfer"),
    path("<int:pk>/delete/", EmployeeDeleteView.as_view(), name="employee_delete"),
    path("<int:pk>/status/update/", employee_status_update, name="employee_status_update"),
    path("<int:pk>/profile-section/employee-information/update/", employee_profile_employee_information_update, name="employee_profile_employee_information_update"),
    path("<int:pk>/profile-section/identity-information/update/", employee_profile_identity_information_update, name="employee_profile_identity_information_update"),
    path("<int:pk>/documents/create/", employee_document_create, name="employee_document_create"),
    path("<int:pk>/document-requests/create/", employee_document_request_create, name="employee_document_request_create"),
    path("document-requests/<int:request_pk>/review/", employee_document_request_review, name="employee_document_request_review"),
    path("document-requests/<int:request_pk>/cancel/", employee_document_request_cancel, name="employee_document_request_cancel"),
    path("<int:pk>/required-submissions/create/", employee_required_submission_create, name="employee_required_submission_create"),
    path("<int:pk>/leave/create/", employee_leave_create, name="employee_leave_create"),
    path("<int:pk>/actions/create/", employee_action_record_create, name="employee_action_record_create"),
    path("<int:pk>/attendance/create/", employee_attendance_create, name="employee_attendance_create"),
    path("attendance/<int:attendance_pk>/corrections/create/", employee_attendance_correction_create, name="employee_attendance_correction_create"),
    path("attendance/corrections/<int:correction_pk>/apply/", employee_attendance_correction_apply, name="employee_attendance_correction_apply"),
    path("attendance/corrections/<int:correction_pk>/reject/", employee_attendance_correction_reject, name="employee_attendance_correction_reject"),
    path("<int:pk>/history/create/", employee_history_create, name="employee_history_create"),

    path("<int:employee_pk>/documents/<int:document_pk>/update/", employee_document_update, name="employee_document_update"),
    path("<int:employee_pk>/documents/<int:document_pk>/delete/", employee_document_delete, name="employee_document_delete"),
    path("required-submissions/<int:request_pk>/submit/", employee_required_submission_submit, name="employee_required_submission_submit"),
    path("required-submissions/<int:request_pk>/review/", employee_required_submission_review, name="employee_required_submission_review"),
    path("<int:employee_pk>/leave/<int:leave_pk>/approve/", employee_leave_approve, name="employee_leave_approve"),
    path("<int:employee_pk>/leave/<int:leave_pk>/reject/", employee_leave_reject, name="employee_leave_reject"),
    path("<int:employee_pk>/leave/<int:leave_pk>/cancel/", employee_leave_cancel, name="employee_leave_cancel"),
]
