# Generated by Django 6.0.3 on 2026-04-20 19:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_delete_branchattendanceshiftsetting'),
        ('organization', '0009_branch_attendance_location_settings'),
        ('payroll', '0003_payrollobligation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('bonus_type', models.CharField(choices=[('performance', 'Performance'), ('commission', 'Commission'), ('seasonal', 'Seasonal'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('awarded_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('award_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('hold', 'On Hold')], default='active', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_bonuses', to='organization.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_bonuses', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Payroll Bonus',
                'verbose_name_plural': 'Payroll Bonuses',
                'ordering': ['employee__full_name', '-award_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='payroll_bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_adjustments', to='payroll.payrollbonus'),
        ),
    ]
