# Generated by Django 6.0.3 on 2026-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_payrollbonus_payrolladjustment_payroll_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollperiod",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="snapshot_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="snapshot_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
