# Generated by Django 6.0.3 on 2026-04-22 22:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollperiod_approved_at_payrollline_snapshot_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='pifss_employee_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='pifss_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollprofile',
            name='pifss_employee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollprofile',
            name='pifss_employer_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1150'), max_digits=5),
        ),
    ]
