# Generated by Django 6.0.3 on 2026-04-24 12:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_employee_options_and_more'),
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
        ('payroll', '0006_payrollline_pifss_employee_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbonus',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='pifss_employee_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='pifss_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='fixed_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='IBAN must use uppercase letters and numbers without spaces.', regex='^[A-Z]{2}[0-9A-Z]{13,32}$')]),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='pifss_employee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='pifss_employer_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1150'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['payroll_line', 'adjustment_type'], name='payroll_pay_payroll_1d5196_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['payroll_obligation'], name='payroll_pay_payroll_36d366_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['payroll_bonus'], name='payroll_pay_payroll_261251_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbonus',
            index=models.Index(fields=['employee', 'status'], name='payroll_pay_employe_11a4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbonus',
            index=models.Index(fields=['company', 'status', '-award_date'], name='payroll_pay_company_b2924f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['payroll_period', 'employee'], name='payroll_pay_payroll_a31800_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['employee', '-created_at'], name='payroll_pay_employe_9e9cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollobligation',
            index=models.Index(fields=['employee', 'status'], name='payroll_pay_employe_623734_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollobligation',
            index=models.Index(fields=['company', 'status', 'start_date'], name='payroll_pay_company_106340_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'status', '-period_start'], name='payroll_pay_company_ec9969_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['pay_date', 'status'], name='payroll_pay_pay_dat_7bc354_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollprofile',
            index=models.Index(fields=['company', 'status'], name='payroll_pay_company_64b814_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollprofile',
            index=models.Index(fields=['employee', 'status'], name='payroll_pay_employe_468649_idx'),
        ),
    ]
