# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces the legacy unique_together declaration on PayrollLine
# with an equivalent named UniqueConstraint. The business rule remains one
# payroll line per payroll period and employee.
#
# No data backfill is required because the same uniqueness rule was already
# represented by the previous schema.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_alter_branchschedulegridcell_unique_together_and_more'),
        ('payroll', '0007_alter_payrollbonus_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollline',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('payroll_period', 'employee'), name='payroll_line_period_employee_uniq'),
        ),
    ]
