# Generated by Django 6.0.3 on 2026-04-24 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_employee_options_and_more'),
        ('operations', '0001_initial'),
        ('organization', '0010_alter_branch_options_alter_branchdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchpost',
            options={'ordering': ['-is_pinned', '-updated_at', '-created_at', '-id'], 'verbose_name': 'Branch Post', 'verbose_name_plural': 'Branch Posts'},
        ),
        migrations.AlterModelOptions(
            name='branchpostacknowledgement',
            options={'ordering': ['-acknowledged_at', '-id'], 'verbose_name': 'Branch Post Acknowledgement', 'verbose_name_plural': 'Branch Post Acknowledgements'},
        ),
        migrations.AlterModelOptions(
            name='branchpostreply',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Branch Post Reply', 'verbose_name_plural': 'Branch Post Replies'},
        ),
        migrations.AlterModelOptions(
            name='branchtaskaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Branch Task Action', 'verbose_name_plural': 'Branch Task Actions'},
        ),
        migrations.AddIndex(
            model_name='branchpost',
            index=models.Index(fields=['branch', 'status', '-updated_at'], name='operations__branch__0459d8_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpost',
            index=models.Index(fields=['assignee', 'status', 'due_date'], name='operations__assigne_95ba32_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpost',
            index=models.Index(fields=['post_type', 'status'], name='operations__post_ty_42b05b_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpostreply',
            index=models.Index(fields=['post', 'created_at'], name='operations__post_id_c4174b_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtaskaction',
            index=models.Index(fields=['post', '-created_at'], name='operations__post_id_abbc09_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtaskaction',
            index=models.Index(fields=['action_type', '-created_at'], name='operations__action__6dfd8a_idx'),
        ),
    ]
