# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces the legacy unique_together declaration on branch post
# acknowledgements with an equivalent named UniqueConstraint. The rule remains:
# one acknowledgement row per post/employee pair.
#
# No data backfill is required because the same uniqueness rule was already
# enforced by the legacy declaration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_alter_branchschedulegridcell_unique_together_and_more'),
        ('operations', '0002_alter_branchpost_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchpostacknowledgement',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branchpostacknowledgement',
            constraint=models.UniqueConstraint(fields=('post', 'employee'), name='ops_post_ack_post_employee_uniq'),
        ),
    ]
