# Generated by Django 6.0.3 on 2026-04-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationpreference_delivery_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="calendar_in_app_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="employee_in_app_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="hr_in_app_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="operations_in_app_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="request_in_app_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="schedule_in_app_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
