# Generated by Django 6.0.3 on 2026-04-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_inappnotification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
