# Generated by Django 6.0.3 on 2026-04-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_inappnotification_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='category',
            field=models.CharField(choices=[('payroll', 'Payroll'), ('request', 'Requests'), ('operations', 'Operations'), ('schedule', 'Schedule'), ('employee', 'Employee Updates'), ('hr', 'HR'), ('contract', 'Contract'), ('calendar', 'Calendar')], default='payroll', max_length=40),
        ),
    ]
