# Generated by Django 6.0.3 on 2026-04-23 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_inappnotification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='email_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='email_failed_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='contract_in_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'is_read', 'is_deleted'], name='notificatio_recipie_be18d9_idx'),
        ),
    ]
