# Generated by Django 6.0.3 on 2026-04-24 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_inappnotification_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'ordering': ['user__email'], 'verbose_name': 'Notification Preference', 'verbose_name_plural': 'Notification Preferences'},
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'is_deleted', '-created_at'], name='notificatio_recipie_4e9d76_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['category', 'level', '-created_at'], name='notificatio_categor_71b10f_idx'),
        ),
    ]
