# Generated by Django 6.0.3 on 2026-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0002_recalculate_leave_totals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalholiday',
            options={'ordering': ['holiday_date', 'title', 'id'], 'verbose_name': 'Regional Holiday', 'verbose_name_plural': 'Regional Holidays'},
        ),
        migrations.AddIndex(
            model_name='regionalholiday',
            index=models.Index(fields=['calendar', 'holiday_date'], name='workcalenda_calenda_2046a9_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalholiday',
            index=models.Index(fields=['is_non_working_day', 'holiday_date'], name='workcalenda_is_non__f4244f_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalworkcalendar',
            index=models.Index(fields=['is_active', 'region_code'], name='workcalenda_is_acti_cf9139_idx'),
        ),
    ]
