# Generated by Django 6.0.3 on 2026-04-24 12:20
#
# Phase 2 model-quality migration.
#
# This migration replaces the legacy unique_together declaration on regional
# holidays with an equivalent named UniqueConstraint. The rule remains one
# holiday title per calendar/date pair.
#
# No data backfill is required because this preserves an existing uniqueness
# rule instead of adding a stricter one.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0003_alter_regionalholiday_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionalholiday',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='regionalholiday',
            constraint=models.UniqueConstraint(fields=('calendar', 'holiday_date', 'title'), name='workcal_holiday_calendar_date_title_uniq'),
        ),
    ]
